/**
 * XDS Tailwind v3 preset (CJS — 소비자 config가 CJS/ESM 둘 다 사용 가능).
 * 토큰 CSS 변수(tokens.css :root/[data-brand]/.dark)를 Tailwind 유틸리티로 노출.
 * 사용: tailwind.config의 presets: [require("@design/xds/preset")]
 */
// xds-typography-composite: 1
const plugin = require("tailwindcss/plugin");

const iconUtilities = {
  ".icon-default": {
    "color": "var(--icon-default)"
  },
  ".icon-subtle": {
    "color": "var(--icon-subtle)"
  },
  ".icon-disabled": {
    "color": "var(--icon-disabled)"
  },
  ".icon-inverse": {
    "color": "var(--icon-inverse)"
  },
  ".icon-on-color": {
    "color": "var(--icon-on-color)"
  },
  ".icon-static-white": {
    "color": "var(--icon-static-white)"
  },
  ".icon-brand": {
    "color": "var(--icon-brand)"
  },
  ".icon-info": {
    "color": "var(--icon-info)"
  },
  ".icon-success": {
    "color": "var(--icon-success)"
  },
  ".icon-warning": {
    "color": "var(--icon-warning)"
  },
  ".icon-danger": {
    "color": "var(--icon-danger)"
  },
  ".icon-accent-violet": {
    "color": "var(--icon-accent-violet)"
  },
  ".icon-accent-pink": {
    "color": "var(--icon-accent-pink)"
  },
  ".icon-accent-teal": {
    "color": "var(--icon-accent-teal)"
  }
};

module.exports = {
  theme: {
    extend: {
  "fontFamily": {
    "sans": [
      "\"Pretendard Variable\"",
      "Pretendard",
      "-apple-system",
      "BlinkMacSystemFont",
      "system-ui",
      "\"Apple SD Gothic Neo\"",
      "\"Noto Sans KR\"",
      "\"Malgun Gothic\"",
      "sans-serif"
    ]
  },
  "colors": {
    "jk-blue-50": "var(--primitive-jkblue-50)",
    "jk-blue-100": "var(--primitive-jkblue-100)",
    "jk-blue-200": "var(--primitive-jkblue-200)",
    "jk-blue-300": "var(--primitive-jkblue-300)",
    "jk-blue-400": "var(--primitive-jkblue-400)",
    "jk-blue-500": "var(--primitive-jkblue-500)",
    "jk-blue-600": "var(--primitive-jkblue-600)",
    "jk-blue-700": "var(--primitive-jkblue-700)",
    "jk-blue-800": "var(--primitive-jkblue-800)",
    "jk-blue-900": "var(--primitive-jkblue-900)",
    "jk-blue-950": "var(--primitive-jkblue-950)",
    "am-orange-50": "var(--primitive-amorange-50)",
    "am-orange-100": "var(--primitive-amorange-100)",
    "am-orange-200": "var(--primitive-amorange-200)",
    "am-orange-300": "var(--primitive-amorange-300)",
    "am-orange-400": "var(--primitive-amorange-400)",
    "am-orange-500": "var(--primitive-amorange-500)",
    "am-orange-600": "var(--primitive-amorange-600)",
    "am-orange-700": "var(--primitive-amorange-700)",
    "am-orange-800": "var(--primitive-amorange-800)",
    "am-orange-900": "var(--primitive-amorange-900)",
    "am-orange-950": "var(--primitive-amorange-950)",
    "jp-green-50": "var(--primitive-jpgreen-50)",
    "jp-green-100": "var(--primitive-jpgreen-100)",
    "jp-green-200": "var(--primitive-jpgreen-200)",
    "jp-green-300": "var(--primitive-jpgreen-300)",
    "jp-green-400": "var(--primitive-jpgreen-400)",
    "jp-green-500": "var(--primitive-jpgreen-500)",
    "jp-green-600": "var(--primitive-jpgreen-600)",
    "jp-green-700": "var(--primitive-jpgreen-700)",
    "jp-green-800": "var(--primitive-jpgreen-800)",
    "jp-green-900": "var(--primitive-jpgreen-900)",
    "jp-green-950": "var(--primitive-jpgreen-950)",
    "gray-50": "var(--primitive-gray-50)",
    "gray-100": "var(--primitive-gray-100)",
    "gray-200": "var(--primitive-gray-200)",
    "gray-300": "var(--primitive-gray-300)",
    "gray-400": "var(--primitive-gray-400)",
    "gray-500": "var(--primitive-gray-500)",
    "gray-600": "var(--primitive-gray-600)",
    "gray-700": "var(--primitive-gray-700)",
    "gray-800": "var(--primitive-gray-800)",
    "gray-900": "var(--primitive-gray-900)",
    "gray-950": "var(--primitive-gray-950)",
    "blue-50": "var(--primitive-blue-50)",
    "blue-100": "var(--primitive-blue-100)",
    "blue-200": "var(--primitive-blue-200)",
    "blue-300": "var(--primitive-blue-300)",
    "blue-400": "var(--primitive-blue-400)",
    "blue-500": "var(--primitive-blue-500)",
    "blue-600": "var(--primitive-blue-600)",
    "blue-700": "var(--primitive-blue-700)",
    "blue-800": "var(--primitive-blue-800)",
    "blue-900": "var(--primitive-blue-900)",
    "blue-950": "var(--primitive-blue-950)",
    "red-50": "var(--primitive-red-50)",
    "red-100": "var(--primitive-red-100)",
    "red-200": "var(--primitive-red-200)",
    "red-300": "var(--primitive-red-300)",
    "red-400": "var(--primitive-red-400)",
    "red-500": "var(--primitive-red-500)",
    "red-600": "var(--primitive-red-600)",
    "red-700": "var(--primitive-red-700)",
    "red-800": "var(--primitive-red-800)",
    "red-900": "var(--primitive-red-900)",
    "red-950": "var(--primitive-red-950)",
    "green-50": "var(--primitive-green-50)",
    "green-100": "var(--primitive-green-100)",
    "green-200": "var(--primitive-green-200)",
    "green-300": "var(--primitive-green-300)",
    "green-400": "var(--primitive-green-400)",
    "green-500": "var(--primitive-green-500)",
    "green-600": "var(--primitive-green-600)",
    "green-700": "var(--primitive-green-700)",
    "green-800": "var(--primitive-green-800)",
    "green-900": "var(--primitive-green-900)",
    "green-950": "var(--primitive-green-950)",
    "yellow-50": "var(--primitive-yellow-50)",
    "yellow-100": "var(--primitive-yellow-100)",
    "yellow-200": "var(--primitive-yellow-200)",
    "yellow-300": "var(--primitive-yellow-300)",
    "yellow-400": "var(--primitive-yellow-400)",
    "yellow-500": "var(--primitive-yellow-500)",
    "yellow-600": "var(--primitive-yellow-600)",
    "yellow-700": "var(--primitive-yellow-700)",
    "yellow-800": "var(--primitive-yellow-800)",
    "yellow-900": "var(--primitive-yellow-900)",
    "yellow-950": "var(--primitive-yellow-950)",
    "violet-50": "var(--primitive-violet-50)",
    "violet-100": "var(--primitive-violet-100)",
    "violet-200": "var(--primitive-violet-200)",
    "violet-300": "var(--primitive-violet-300)",
    "violet-400": "var(--primitive-violet-400)",
    "violet-500": "var(--primitive-violet-500)",
    "violet-600": "var(--primitive-violet-600)",
    "violet-700": "var(--primitive-violet-700)",
    "violet-800": "var(--primitive-violet-800)",
    "violet-900": "var(--primitive-violet-900)",
    "violet-950": "var(--primitive-violet-950)",
    "pink-50": "var(--primitive-pink-50)",
    "pink-100": "var(--primitive-pink-100)",
    "pink-200": "var(--primitive-pink-200)",
    "pink-300": "var(--primitive-pink-300)",
    "pink-400": "var(--primitive-pink-400)",
    "pink-500": "var(--primitive-pink-500)",
    "pink-600": "var(--primitive-pink-600)",
    "pink-700": "var(--primitive-pink-700)",
    "pink-800": "var(--primitive-pink-800)",
    "pink-900": "var(--primitive-pink-900)",
    "pink-950": "var(--primitive-pink-950)",
    "teal-50": "var(--primitive-teal-50)",
    "teal-100": "var(--primitive-teal-100)",
    "teal-200": "var(--primitive-teal-200)",
    "teal-300": "var(--primitive-teal-300)",
    "teal-400": "var(--primitive-teal-400)",
    "teal-500": "var(--primitive-teal-500)",
    "teal-600": "var(--primitive-teal-600)",
    "teal-700": "var(--primitive-teal-700)",
    "teal-800": "var(--primitive-teal-800)",
    "teal-900": "var(--primitive-teal-900)",
    "teal-950": "var(--primitive-teal-950)",
    "opacity-black-50": "var(--primitive-opacity-black-50)",
    "opacity-black-100": "var(--primitive-opacity-black-100)",
    "opacity-black-200": "var(--primitive-opacity-black-200)",
    "opacity-black-300": "var(--primitive-opacity-black-300)",
    "opacity-black-400": "var(--primitive-opacity-black-400)",
    "opacity-black-500": "var(--primitive-opacity-black-500)",
    "opacity-black-600": "var(--primitive-opacity-black-600)",
    "opacity-white-50": "var(--primitive-opacity-white-50)",
    "opacity-white-100": "var(--primitive-opacity-white-100)",
    "opacity-white-200": "var(--primitive-opacity-white-200)",
    "opacity-white-300": "var(--primitive-opacity-white-300)",
    "opacity-white-400": "var(--primitive-opacity-white-400)",
    "opacity-white-500": "var(--primitive-opacity-white-500)",
    "opacity-white-600": "var(--primitive-opacity-white-600)",
    "brand-50": "var(--brand-50)",
    "brand-300": "var(--brand-300)",
    "brand-500": "var(--brand-500)",
    "brand-700": "var(--brand-700)",
    "brand-800": "var(--brand-800)",
    "brand-900": "var(--brand-900)",
    "background": "var(--background-default)",
    "background-subtle": "var(--background-subtle)",
    "background-inverse": "var(--background-inverse)",
    "background-brand-subtle": "var(--background-brand-subtle)",
    "background-dim": "var(--background-dim)",
    "typography": "var(--typography-default)",
    "typography-default": "var(--typography-default)",
    "typography-secondary": "var(--typography-secondary)",
    "typography-subtle": "var(--typography-subtle)",
    "typography-disabled": "var(--typography-disabled)",
    "typography-inverse": "var(--typography-inverse)",
    "typography-static-white": "var(--typography-static-white)",
    "typography-brand": "var(--typography-brand)",
    "typography-info": "var(--typography-info)",
    "typography-success": "var(--typography-success)",
    "typography-warning": "var(--typography-warning)",
    "typography-error": "var(--typography-error)",
    "typography-accent-violet": "var(--typography-accent-violet)",
    "typography-accent-pink": "var(--typography-accent-pink)",
    "typography-accent-teal": "var(--typography-accent-teal)",
    "fill-element": "var(--fill-element-default)",
    "fill-element-default": "var(--fill-element-default)",
    "fill-element-surface": "var(--fill-element-surface)",
    "fill-element-surface-raised": "var(--fill-element-surface-raised)",
    "fill-element-surface-inverse": "var(--fill-element-surface-inverse)",
    "fill-element-static-white": "var(--fill-element-static-white)",
    "fill-element-brand": "var(--fill-element-brand)",
    "fill-element-brand-subtle": "var(--fill-element-brand-subtle)",
    "fill-element-info": "var(--fill-element-info)",
    "fill-element-info-subtle": "var(--fill-element-info-subtle)",
    "fill-element-success": "var(--fill-element-success)",
    "fill-element-success-subtle": "var(--fill-element-success-subtle)",
    "fill-element-warning": "var(--fill-element-warning)",
    "fill-element-warning-subtle": "var(--fill-element-warning-subtle)",
    "fill-element-danger": "var(--fill-element-danger)",
    "fill-element-danger-subtle": "var(--fill-element-danger-subtle)",
    "fill-element-accent-violet": "var(--fill-element-accent-violet)",
    "fill-element-accent-violet-subtle": "var(--fill-element-accent-violet-subtle)",
    "fill-element-accent-pink": "var(--fill-element-accent-pink)",
    "fill-element-accent-pink-subtle": "var(--fill-element-accent-pink-subtle)",
    "fill-element-accent-teal": "var(--fill-element-accent-teal)",
    "fill-element-accent-teal-subtle": "var(--fill-element-accent-teal-subtle)",
    "fill-element-hover-weak": "var(--fill-element-hover-weak)",
    "fill-element-hover-strong": "var(--fill-element-hover-strong)",
    "fill-element-disabled-weak": "var(--fill-element-disabled-weak)",
    "fill-element-disabled-strong": "var(--fill-element-disabled-strong)",
    "fill-layer": "var(--fill-layer-default)",
    "fill-layer-default": "var(--fill-layer-default)",
    "fill-layer-surface": "var(--fill-layer-surface)",
    "fill-layer-surface-raised": "var(--fill-layer-surface-raised)",
    "fill-layer-surface-inverse": "var(--fill-layer-surface-inverse)",
    "fill-layer-brand-subtle": "var(--fill-layer-brand-subtle)",
    "border": "var(--border-default)",
    "border-default": "var(--border-default)",
    "border-subtle": "var(--border-subtle)",
    "border-strong": "var(--border-strong)",
    "border-disabled": "var(--border-disabled)",
    "border-brand": "var(--border-brand)",
    "border-brand-subtle": "var(--border-brand-subtle)",
    "border-info": "var(--border-info)",
    "border-success": "var(--border-success)",
    "border-warning": "var(--border-warning)",
    "border-danger": "var(--border-danger)",
    "border-danger-subtle": "var(--border-danger-subtle)"
  },
  "borderRadius": {
    "xs": "var(--radius-xs)",
    "sm": "var(--radius-sm)",
    "md": "var(--radius-md)",
    "lg": "var(--radius-lg)",
    "xl": "var(--radius-xl)",
    "xxl": "var(--radius-xxl)",
    "full": "var(--radius-full)",
    "brand-xs": "var(--radius-brand-xs)",
    "brand-sm": "var(--radius-brand-sm)",
    "brand-md": "var(--radius-brand-md)",
    "brand-lg": "var(--radius-brand-lg)"
  },
  "spacing": {
    "0": "var(--spacing-0)",
    "0.5": "var(--spacing-0-5)",
    "1": "var(--spacing-1)",
    "1.5": "var(--spacing-1-5)",
    "2": "var(--spacing-2)",
    "3": "var(--spacing-3)",
    "4": "var(--spacing-4)",
    "5": "var(--spacing-5)",
    "6": "var(--spacing-6)",
    "7": "var(--spacing-7)",
    "8": "var(--spacing-8)",
    "9": "var(--spacing-9)",
    "10": "var(--spacing-10)",
    "12": "var(--spacing-12)",
    "13": "var(--spacing-13)",
    "14": "var(--spacing-14)",
    "16": "var(--spacing-16)",
    "20": "var(--spacing-20)",
    "n025": "var(--spacing-n025)"
  },
  "fontSize": {
    "caption-base": ["var(--font-size-caption-base)", { "lineHeight": "var(--font-line-height-18)", "letterSpacing": "var(--font-letter-spacing-normal)" }],
    "caption-lg": ["var(--font-size-caption-lg)", { "lineHeight": "var(--font-line-height-20)", "letterSpacing": "var(--font-letter-spacing-normal)" }],
    "body-xs": ["var(--font-size-body-xs)", { "lineHeight": "var(--font-line-height-20)", "letterSpacing": "var(--font-letter-spacing-normal)" }],
    "body-sm": ["var(--font-size-body-sm)", { "lineHeight": "var(--font-line-height-22)", "letterSpacing": "var(--font-letter-spacing-normal)" }],
    "body-base": ["var(--font-size-body-base)", { "lineHeight": "var(--font-line-height-24)", "letterSpacing": "var(--font-letter-spacing-normal)" }],
    "body-lg": ["var(--font-size-body-lg)", { "lineHeight": "var(--font-line-height-24)", "letterSpacing": "var(--font-letter-spacing-normal)" }],
    "heading-xs": ["var(--font-size-heading-xs)", { "lineHeight": "var(--font-line-height-24)", "letterSpacing": "var(--font-letter-spacing-normal)" }],
    "heading-sm": ["var(--font-size-heading-sm)", { "lineHeight": "var(--font-line-height-28)", "letterSpacing": "var(--font-letter-spacing-tight)" }],
    "heading-base": ["var(--font-size-heading-base)", { "lineHeight": "var(--font-line-height-32)", "letterSpacing": "var(--font-letter-spacing-tight)" }],
    "heading-lg": ["var(--font-size-heading-lg)", { "lineHeight": "var(--font-line-height-36)", "letterSpacing": "var(--font-letter-spacing-tight)" }],
    "heading-xl": ["var(--font-size-heading-xl)", { "lineHeight": "var(--font-line-height-40)", "letterSpacing": "var(--font-letter-spacing-tight)" }]
  },
  "lineHeight": {
    "18": "var(--font-line-height-18)",
    "20": "var(--font-line-height-20)",
    "22": "var(--font-line-height-22)",
    "24": "var(--font-line-height-24)",
    "28": "var(--font-line-height-28)",
    "32": "var(--font-line-height-32)",
    "36": "var(--font-line-height-36)",
    "40": "var(--font-line-height-40)"
  },
  "letterSpacing": {
    "tight": "var(--font-letter-spacing-tight)",
    "normal": "var(--font-letter-spacing-normal)",
    "wide": "var(--font-letter-spacing-wide)"
  },
  "boxShadow": {
    "xs": "0 0 3px rgb(0 0 0 / 0.02), 0 1px 2px rgb(0 0 0 / 0.08)",
    "sm": "0 0 4px rgb(0 0 0 / 0.02), 0 2px 4px rgb(0 0 0 / 0.08)",
    "md": "0 0 4px rgb(0 0 0 / 0.04), 0 4px 8px -1px rgb(0 0 0 / 0.08)",
    "lg": "0 0 6px rgb(0 0 0 / 0.04), 0 8px 16px -1px rgb(0 0 0 / 0.08)",
    "xl": "0 0 8px rgb(0 0 0 / 0.04), 0 16px 32px -4px rgb(0 0 0 / 0.1)",
    "2xl": "0 0 12px rgb(0 0 0 / 0.06), 0 24px 40px -4px rgb(0 0 0 / 0.1)",
    "up": "0 -2px 12px rgb(0 0 0 / 0.12)"
  }
},
  },
  plugins: [plugin(({ addUtilities }) => addUtilities(iconUtilities))],
};
