// Generate React components for all 92 Phosphor icons × 5 weights.
//
// For each icon name we fetch 5 SVGs from
//   https://raw.githubusercontent.com/phosphor-icons/core/main/assets/<weight>/<name>{-<weight>}.svg
// extract the inner markup, and emit src/icons/<PascalName>.tsx with a
// forwardRef component that swaps inner content by `weight` prop.
//
// Network failures for individual icons are reported but don't abort the run.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PKG_ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(PKG_ROOT, "src", "icons");

const WEIGHTS = ["thin", "light", "regular", "bold", "fill"] as const;
type Weight = (typeof WEIGHTS)[number];

const ICON_NAMES = [
  // people / team (10)
  "user", "users", "user-circle", "user-check", "user-plus",
  "identification-card", "address-book", "user-list", "users-three", "user-gear",
  // role / company (8)
  "briefcase", "building", "buildings", "storefront", "factory",
  "suitcase", "house", "house-simple",
  // resume / document (10)
  "file-text", "file-doc", "file-pdf", "note", "notepad",
  "notebook", "paperclip", "bookmark", "bookmark-simple", "archive",
  // search / filter (8)
  "magnifying-glass", "funnel", "sliders-horizontal", "tag",
  "list-magnifying-glass", "sort-ascending", "sort-descending", "list-bullets",
  // action / share (10)
  "paper-plane-tilt", "share-network", "heart", "star", "thumbs-up",
  "check", "pencil-simple", "trash", "export", "download-simple",
  // ai / recommend (6)
  "sparkle", "magic-wand", "robot", "lightning", "lightbulb", "brain",
  // interview / schedule (8)
  "calendar", "calendar-check", "calendar-blank", "clock",
  "hourglass", "video-camera", "microphone", "timer",
  // notification / status (8)
  "bell", "check-circle", "x-circle", "warning",
  "info", "question", "seal-check", "chat-circle-dots",
  // navigation / dashboard (6)
  "gear", "chart-bar", "chart-line", "chart-pie", "squares-four", "list",
  // arrow / direction (10)
  "arrow-right", "arrow-left", "arrow-up", "arrow-down",
  "caret-right", "caret-left", "caret-down", "caret-up", "plus", "x",
  // communication / link (4)
  "envelope", "phone", "link", "at",
  // security / account (4)
  "lock", "key", "shield", "sign-out",
] as const;

type IconName = (typeof ICON_NAMES)[number];

function toPascal(name: string): string {
  return name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function urlFor(name: string, weight: Weight): string {
  const file = weight === "regular" ? `${name}.svg` : `${name}-${weight}.svg`;
  return `https://raw.githubusercontent.com/phosphor-icons/core/main/assets/${weight}/${file}`;
}

async function fetchSvg(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} for ${url}`);
  }
  return res.text();
}

// Extract inner JSX-ready markup from a Phosphor SVG file.
// Phosphor SVGs are like:
//   <svg xmlns="..." viewBox="0 0 256 256"><rect .../><path d=".."/></svg>
// We grab everything between the outer <svg ...> opening tag and </svg>.
function extractInner(svg: string): string {
  const trimmed = svg.trim();
  const openEnd = trimmed.indexOf(">");
  const closeStart = trimmed.lastIndexOf("</svg>");
  if (openEnd < 0 || closeStart < 0) {
    throw new Error("Malformed SVG: no <svg> open/close found");
  }
  let inner = trimmed.slice(openEnd + 1, closeStart).trim();
  // Force fill/stroke on children to currentColor so the `color` prop wins.
  inner = inner
    .replace(/fill="(?!none")[^"]*"/g, 'fill="currentColor"')
    .replace(/stroke="(?!none")[^"]*"/g, 'stroke="currentColor"');
  // Convert any hyphenated SVG attrs to camelCase for JSX.
  inner = inner.replace(/\b([a-z]+)-([a-z])/g, (_m, a: string, b: string) => {
    // Keep data-* and aria-* hyphenated (rare in Phosphor).
    if (a === "data" || a === "aria") return `${a}-${b}`;
    return a + b.toUpperCase();
  });
  return inner;
}

function emitComponent(name: IconName, weightMap: Record<Weight, string>): string {
  const pascal = toPascal(name);
  const blocks = WEIGHTS.map(
    (w) => `    ${w}: (\n      <>\n        ${weightMap[w]}\n      </>\n    ),`,
  ).join("\n");
  return `// AUTO-GENERATED by scripts/generate.ts. Do not edit.
import { forwardRef } from "react";
import type { IconProps } from "../types";

export const ${pascal} = forwardRef<SVGSVGElement, IconProps>(function ${pascal}(
  { size = 24, weight = "regular", color = "currentColor", ...props },
  ref,
) {
  const paths: Record<NonNullable<IconProps["weight"]>, JSX.Element> = {
${blocks}
  };
  return (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 0 256 256"
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      {paths[weight]}
    </svg>
  );
});
${pascal}.displayName = "${pascal}";
`;
}

async function fetchWithRetry(url: string, attempts = 2): Promise<string> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fetchSvg(url);
    } catch (e) {
      lastErr = e;
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error(String(lastErr));
}

async function main() {
  await fs.rm(OUT_DIR, { recursive: true, force: true });
  await fs.mkdir(OUT_DIR, { recursive: true });

  const failed: { name: string; weight: Weight; reason: string }[] = [];
  const succeeded: IconName[] = [];

  // Modest concurrency to be polite to raw.githubusercontent.com.
  const CONCURRENCY = 10;
  const queue = [...ICON_NAMES];

  async function worker() {
    while (queue.length) {
      const name = queue.shift();
      if (!name) return;
      const weightMap: Partial<Record<Weight, string>> = {};
      let hardFail = false;
      for (const w of WEIGHTS) {
        try {
          const svg = await fetchWithRetry(urlFor(name, w));
          weightMap[w] = extractInner(svg);
        } catch (e) {
          failed.push({
            name,
            weight: w,
            reason: e instanceof Error ? e.message : String(e),
          });
          if (w === "regular") {
            // Without `regular` we can't sensibly emit a component.
            hardFail = true;
            break;
          }
          // Otherwise fall back to regular if we have it; if not, defer.
        }
      }
      if (hardFail) continue;
      // Fill any missing weights with the regular variant so the component
      // is still usable across all `weight` values.
      const regular = weightMap.regular!;
      for (const w of WEIGHTS) {
        if (!weightMap[w]) weightMap[w] = regular;
      }
      const pascal = toPascal(name);
      const file = path.join(OUT_DIR, `${pascal}.tsx`);
      await fs.writeFile(
        file,
        emitComponent(name, weightMap as Record<Weight, string>),
        "utf8",
      );
      succeeded.push(name);
    }
  }

  console.log(
    `[icons] generating ${ICON_NAMES.length} icons × ${WEIGHTS.length} weights = ${
      ICON_NAMES.length * WEIGHTS.length
    } SVG fetches …`,
  );
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));

  // Write barrel index.
  const sortedSuccess = [...succeeded].sort();
  const indexLines = sortedSuccess.map(
    (n) => `export { ${toPascal(n)} } from "./${toPascal(n)}";`,
  );
  await fs.writeFile(
    path.join(OUT_DIR, "index.ts"),
    "// AUTO-GENERATED by scripts/generate.ts. Do not edit.\n" +
      indexLines.join("\n") +
      "\n",
    "utf8",
  );

  console.log(`[icons] generated ${succeeded.length} / ${ICON_NAMES.length} icons`);
  if (failed.length) {
    console.warn(`[icons] ${failed.length} fetch failures:`);
    for (const f of failed) {
      console.warn(`  - ${f.name} (${f.weight}): ${f.reason}`);
    }
  }
  // Hard-fail only if `regular` was missing for any icon.
  const missingRegular = ICON_NAMES.filter((n) => !succeeded.includes(n));
  if (missingRegular.length) {
    console.error(
      `[icons] ${missingRegular.length} icons have no regular weight (component not emitted): ${missingRegular.join(
        ", ",
      )}`,
    );
    process.exitCode = 1;
  } else {
    console.log("[icons] done ✓");
  }
}

main().catch((err) => {
  console.error("[icons] generate failed:", err);
  process.exit(1);
});
