// AUTO-GENERATED by scripts/generate.ts. Do not edit.
import { forwardRef, type ReactElement } from "react";
import type { IconProps } from "../types";

export const ArrowUp = forwardRef<SVGSVGElement, IconProps>(function ArrowUp(
  { size = 24, weight = "regular", color = "currentColor", ...props },
  ref,
) {
  const paths: Record<NonNullable<IconProps["weight"]>, ReactElement> = {
    thin: (
      <>
        <path d="M202.83,114.83a4,4,0,0,1-5.66,0L132,49.66V216a4,4,0,0,1-8,0V49.66L58.83,114.83a4,4,0,0,1-5.66-5.66l72-72a4,4,0,0,1,5.66,0l72,72A4,4,0,0,1,202.83,114.83Z"/>
      </>
    ),
    light: (
      <>
        <path d="M204.24,116.24a6,6,0,0,1-8.48,0L134,54.49V216a6,6,0,0,1-12,0V54.49L60.24,116.24a6,6,0,0,1-8.48-8.48l72-72a6,6,0,0,1,8.48,0l72,72A6,6,0,0,1,204.24,116.24Z"/>
      </>
    ),
    regular: (
      <>
        <path d="M205.66,117.66a8,8,0,0,1-11.32,0L136,59.31V216a8,8,0,0,1-16,0V59.31L61.66,117.66a8,8,0,0,1-11.32-11.32l72-72a8,8,0,0,1,11.32,0l72,72A8,8,0,0,1,205.66,117.66Z"/>
      </>
    ),
    bold: (
      <>
        <path d="M208.49,120.49a12,12,0,0,1-17,0L140,69V216a12,12,0,0,1-24,0V69L64.49,120.49a12,12,0,0,1-17-17l72-72a12,12,0,0,1,17,0l72,72A12,12,0,0,1,208.49,120.49Z"/>
      </>
    ),
    fill: (
      <>
        <path d="M207.39,115.06A8,8,0,0,1,200,120H136v96a8,8,0,0,1-16,0V120H56a8,8,0,0,1-5.66-13.66l72-72a8,8,0,0,1,11.32,0l72,72A8,8,0,0,1,207.39,115.06Z"/>
      </>
    ),
  };
  return (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 0 256 256"
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      {paths[weight]}
    </svg>
  );
});
ArrowUp.displayName = "ArrowUp";
