// AUTO-GENERATED by scripts/generate.ts. Do not edit.
import { forwardRef, type ReactElement } from "react";
import type { IconProps } from "../types";

export const ArrowDown = forwardRef<SVGSVGElement, IconProps>(function ArrowDown(
  { size = 24, weight = "regular", color = "currentColor", ...props },
  ref,
) {
  const paths: Record<NonNullable<IconProps["weight"]>, ReactElement> = {
    thin: (
      <>
        <path d="M202.83,146.83l-72,72a4,4,0,0,1-5.66,0l-72-72a4,4,0,0,1,5.66-5.66L124,206.34V40a4,4,0,0,1,8,0V206.34l65.17-65.17a4,4,0,0,1,5.66,5.66Z"/>
      </>
    ),
    light: (
      <>
        <path d="M204.24,148.24l-72,72a6,6,0,0,1-8.48,0l-72-72a6,6,0,0,1,8.48-8.48L122,201.51V40a6,6,0,0,1,12,0V201.51l61.76-61.75a6,6,0,0,1,8.48,8.48Z"/>
      </>
    ),
    regular: (
      <>
        <path d="M205.66,149.66l-72,72a8,8,0,0,1-11.32,0l-72-72a8,8,0,0,1,11.32-11.32L120,196.69V40a8,8,0,0,1,16,0V196.69l58.34-58.35a8,8,0,0,1,11.32,11.32Z"/>
      </>
    ),
    bold: (
      <>
        <path d="M208.49,152.49l-72,72a12,12,0,0,1-17,0l-72-72a12,12,0,0,1,17-17L116,187V40a12,12,0,0,1,24,0V187l51.51-51.52a12,12,0,0,1,17,17Z"/>
      </>
    ),
    fill: (
      <>
        <path d="M205.66,149.66l-72,72a8,8,0,0,1-11.32,0l-72-72A8,8,0,0,1,56,136h64V40a8,8,0,0,1,16,0v96h64a8,8,0,0,1,5.66,13.66Z"/>
      </>
    ),
  };
  return (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 0 256 256"
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      {paths[weight]}
    </svg>
  );
});
ArrowDown.displayName = "ArrowDown";
