// AUTO-GENERATED by scripts/generate.ts. Do not edit.
import { forwardRef, type ReactElement } from "react";
import type { IconProps } from "../types";

export const CaretDown = forwardRef<SVGSVGElement, IconProps>(function CaretDown(
  { size = 24, weight = "regular", color = "currentColor", ...props },
  ref,
) {
  const paths: Record<NonNullable<IconProps["weight"]>, ReactElement> = {
    thin: (
      <>
        <path d="M210.83,98.83l-80,80a4,4,0,0,1-5.66,0l-80-80a4,4,0,0,1,5.66-5.66L128,170.34l77.17-77.17a4,4,0,1,1,5.66,5.66Z"/>
      </>
    ),
    light: (
      <>
        <path d="M212.24,100.24l-80,80a6,6,0,0,1-8.48,0l-80-80a6,6,0,0,1,8.48-8.48L128,167.51l75.76-75.75a6,6,0,0,1,8.48,8.48Z"/>
      </>
    ),
    regular: (
      <>
        <path d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"/>
      </>
    ),
    bold: (
      <>
        <path d="M216.49,104.49l-80,80a12,12,0,0,1-17,0l-80-80a12,12,0,0,1,17-17L128,159l71.51-71.52a12,12,0,0,1,17,17Z"/>
      </>
    ),
    fill: (
      <>
        <path d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,48,88H208a8,8,0,0,1,5.66,13.66Z"/>
      </>
    ),
  };
  return (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 0 256 256"
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      {paths[weight]}
    </svg>
  );
});
CaretDown.displayName = "CaretDown";
