// AUTO-GENERATED by scripts/generate.ts. Do not edit.
import { forwardRef, type ReactElement } from "react";
import type { IconProps } from "../types";

export const Plus = forwardRef<SVGSVGElement, IconProps>(function Plus(
  { size = 24, weight = "regular", color = "currentColor", ...props },
  ref,
) {
  const paths: Record<NonNullable<IconProps["weight"]>, ReactElement> = {
    thin: (
      <>
        <path d="M220,128a4,4,0,0,1-4,4H132v84a4,4,0,0,1-8,0V132H40a4,4,0,0,1,0-8h84V40a4,4,0,0,1,8,0v84h84A4,4,0,0,1,220,128Z"/>
      </>
    ),
    light: (
      <>
        <path d="M222,128a6,6,0,0,1-6,6H134v82a6,6,0,0,1-12,0V134H40a6,6,0,0,1,0-12h82V40a6,6,0,0,1,12,0v82h82A6,6,0,0,1,222,128Z"/>
      </>
    ),
    regular: (
      <>
        <path d="M224,128a8,8,0,0,1-8,8H136v80a8,8,0,0,1-16,0V136H40a8,8,0,0,1,0-16h80V40a8,8,0,0,1,16,0v80h80A8,8,0,0,1,224,128Z"/>
      </>
    ),
    bold: (
      <>
        <path d="M228,128a12,12,0,0,1-12,12H140v76a12,12,0,0,1-24,0V140H40a12,12,0,0,1,0-24h76V40a12,12,0,0,1,24,0v76h76A12,12,0,0,1,228,128Z"/>
      </>
    ),
    fill: (
      <>
        <path d="M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM184,136H136v48a8,8,0,0,1-16,0V136H72a8,8,0,0,1,0-16h48V72a8,8,0,0,1,16,0v48h48a8,8,0,0,1,0,16Z"/>
      </>
    ),
  };
  return (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 0 256 256"
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      {paths[weight]}
    </svg>
  );
});
Plus.displayName = "Plus";
